"""
shared/models.py
================
Central data models shared across all agents.
Defines the core Order dataclass and supporting enums so that
`state_agent` and `routing_agent` speak the same language.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Any, List


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class OrderType(str, Enum):
    """Whether a city wants to buy or sell electricity."""
    BUY  = "BUY"
    SELL = "SELL"


class RiskLevel(str, Enum):
    """Demand-spike risk levels as returned by the LLM context JSON."""
    LOW      = "LOW"
    MEDIUM   = "MEDIUM"
    HIGH     = "HIGH"
    CRITICAL = "CRITICAL"


class RiskSeverity(str, Enum):
    """
    Risk severity levels for StimulusFlags and RiskScores.
    Used by White Routing to weight transit path risk.
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ---------------------------------------------------------------------------
# White Routing: Risk-Aware Path Selection Models
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class StimulusFlag:
    """
    Forward-looking risk indicator for a state/transit node.
    
    Used by StimulusRadar to aggregate weather forecasts and
    scraped events into actionable risk signals for Phase 6 routing.
    """
    state_id: str              # State identifier (e.g., "WB", "UP")
    source: str                # "weather", "grid_event", "economic", "political"
    event_type: str            # "cyclone", "heatwave", "outage", "strike", etc.
    severity: RiskSeverity     # Risk severity level
    eta_hours: float           # Hours until event impacts (0 = already happening)
    estimated_impact_mw: float # Expected demand/supply impact in MW
    description: str           # Human-readable description
    expires_at: str            # ISO timestamp when flag should be cleared


@dataclass(frozen=True)
class RiskScore:
    """
    Aggregated risk score for a state.
    
    Computed by StimulusRadar from multiple StimulusFlags.
    Used by Phase 6 to sort and prioritize transit paths.
    """
    state_id: str                    # State identifier
    total_score: float               # 0.0 (safe) to 1.0 (critical)
    severity: RiskSeverity           # Overall severity category
    active_flags: tuple              # Tuple of StimulusFlags (frozen for immutability)
    computed_at: str                 # ISO timestamp when score was computed


# ---------------------------------------------------------------------------
# Order dataclass
# ---------------------------------------------------------------------------

@dataclass
class Order:
    """
    A financial order generated by a StateAgent for one city.

    Attributes
    ----------
    city_id       : Unique identifier string for the city (e.g. "DEL", "MUM").
    order_type    : BUY if the city needs power, SELL if it has surplus.
    quantity_mw   : Amount of power in MW the city wants to trade.
    price_per_mw  : Bid (max willingness to pay) or Ask (min willingness to accept) in ₹/MW.
    reason        : Human-readable explanation of how the price was determined.
    """
    city_id     : str
    order_type  : OrderType
    quantity_mw : float
    price_per_mw: float
    reason      : str

    def __repr__(self) -> str:
        direction = "bids" if self.order_type == OrderType.BUY else "asks"
        return (
            f"<Order [{self.order_type.value}] {self.city_id} "
            f"{direction} ₹{self.price_per_mw}/MW for {self.quantity_mw:.1f} MW | {self.reason}>"
        )


# ---------------------------------------------------------------------------
# DispatchRecord dataclass  (populated by RoutingAgent after execution)
# ---------------------------------------------------------------------------

@dataclass
class DispatchRecord:
    """
    Immutable record of one successfully executed inter-city power transfer.
    Used for logging, audit trails, and downstream analytics.
    """
    buyer_city_id     : str
    seller_city_id    : str
    transfer_mw       : float
    cleared_price_mw  : float   # ₹/MW  (Ask + path_cost + optional carbon_tax)
    seller_ask        : float
    path_cost         : float
    carbon_tax        : float   # 0 if green_mode is False
    buyer_bid         : float
    path_description  : str     # e.g. "MUM->NAG->DEL"
    llm_safety_status : str     # "APPROVED" or rejection reason
    dlr_applied       : bool    # True if Dynamic Line Rating reduced capacity
    effective_capacity: float   # MW after DLR adjustment
    requested_mw      : float = 0.0
    line_cap_mw       : float = 0.0
    approved_mw       : float = 0.0
    residual_deficit_mw: float = 0.0
    dispatch_hour     : Optional[int] = None
    radar_locked      : bool = False
    radar_alert       : str = ""
    route_agent       : str = "DOUBLE_DQN_PROXY"
    decision_trace    : list[str] = field(default_factory=list)


@dataclass
class SyndicateDispatchRecord:
    """
    Immutable record of a multi-node syndicate trade where multiple sellers
    pool their surplus to serve a single buyer.
    """
    buyer_city_id    : str
    transfer_mw      : float
    cleared_price_mw : float   # The blended negotiated price in ₹/MW
    buyer_bid        : float
    syndicate_sellers: list[str]
    breakdown_log    : str


@dataclass
class StatePosition:
    """
    Deterministic state-level position after calibration and intelligence injection.
    """
    state_id: str
    forecast_7d_mw: list[float]
    avg_forecast_mw: float
    baseline_supply_mw: float
    todays_demand_forecast_mw: float
    adjusted_demand_mw: float
    adjusted_supply_mw: float
    net_position_mw: float
    deficit_mw: float
    surplus_mw: float
    economic_demand_multiplier: float
    generation_multiplier: float
    pre_event_hoard: bool
    dispatch_hour_hint: int
    is_deficit: bool = False
    dr_savings_inr: float = 0.0
    dr_activated_mw: float = 0.0
    current_import_tariff: float = 0.0
    dr_clearing_price: float = 0.0
    reasoning: str = ""
    phase_log: list[str] = field(default_factory=list)


@dataclass
class LoadSheddingRecord:
    """
    Forced load-shedding action mandated by the syndicate decider.
    """
    state_id: str
    shed_mw: float
    level: str
    reason: str
    dispatch_hour: Optional[int] = None
    phase_log: list[str] = field(default_factory=list)


@dataclass
class ProposedTrade:
    """
    Phase-6 schema-bound deterministic trade proposal.
    """
    buyer_state: str
    seller_state: str
    requested_mw: float
    approved_mw: float = 0.0
    reason: str = ""
